Update __init__.py
The try/except block here is failing for the most recent version of Django.

It's trying to import include from django.conf.urls and then failing into the ImportError exception which then causes a compilation error when it tries to import from django.conf.urls.default since that no longer exists.